<?php
/**
 * DR11Response200DataRecipientOrganization
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  cbdesk\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mirakl Marketplace APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest-release
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace cbdesk\Mirakl\Model;

use \ArrayAccess;
use \cbdesk\Mirakl\ObjectSerializer;

/**
 * DR11Response200DataRecipientOrganization Class Doc Comment
 *
 * @category Class
 * @package  cbdesk\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DR11Response200DataRecipientOrganization implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DR11_Response_200_Data_Recipient_Organization';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'address' => '\cbdesk\Mirakl\Model\DR11Response200DataRecipientOrganizationAddress',
        'business_activity_code' => 'string',
        'company_shareholders' => 'string',
        'identification_number' => 'string',
        'is_in_liquidation' => 'bool',
        'legal_form' => 'string',
        'local_tax_number' => 'string',
        'local_tax_number_country' => 'string',
        'name' => 'string',
        'organization_id' => 'string',
        'share_capital' => 'float',
        'share_capital_currency' => 'string',
        'tax_identification_number' => 'string',
        'tax_number_country' => 'string',
        'trade_company_registration_location' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'address' => null,
        'business_activity_code' => null,
        'company_shareholders' => null,
        'identification_number' => null,
        'is_in_liquidation' => null,
        'legal_form' => null,
        'local_tax_number' => null,
        'local_tax_number_country' => null,
        'name' => null,
        'organization_id' => null,
        'share_capital' => null,
        'share_capital_currency' => null,
        'tax_identification_number' => null,
        'tax_number_country' => null,
        'trade_company_registration_location' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'address' => false,
        'business_activity_code' => false,
        'company_shareholders' => false,
        'identification_number' => false,
        'is_in_liquidation' => false,
        'legal_form' => false,
        'local_tax_number' => false,
        'local_tax_number_country' => false,
        'name' => false,
        'organization_id' => false,
        'share_capital' => false,
        'share_capital_currency' => false,
        'tax_identification_number' => false,
        'tax_number_country' => false,
        'trade_company_registration_location' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'address' => 'address',
        'business_activity_code' => 'business_activity_code',
        'company_shareholders' => 'company_shareholders',
        'identification_number' => 'identification_number',
        'is_in_liquidation' => 'is_in_liquidation',
        'legal_form' => 'legal_form',
        'local_tax_number' => 'local_tax_number',
        'local_tax_number_country' => 'local_tax_number_country',
        'name' => 'name',
        'organization_id' => 'organization_id',
        'share_capital' => 'share_capital',
        'share_capital_currency' => 'share_capital_currency',
        'tax_identification_number' => 'tax_identification_number',
        'tax_number_country' => 'tax_number_country',
        'trade_company_registration_location' => 'trade_company_registration_location'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'address' => 'setAddress',
        'business_activity_code' => 'setBusinessActivityCode',
        'company_shareholders' => 'setCompanyShareholders',
        'identification_number' => 'setIdentificationNumber',
        'is_in_liquidation' => 'setIsInLiquidation',
        'legal_form' => 'setLegalForm',
        'local_tax_number' => 'setLocalTaxNumber',
        'local_tax_number_country' => 'setLocalTaxNumberCountry',
        'name' => 'setName',
        'organization_id' => 'setOrganizationId',
        'share_capital' => 'setShareCapital',
        'share_capital_currency' => 'setShareCapitalCurrency',
        'tax_identification_number' => 'setTaxIdentificationNumber',
        'tax_number_country' => 'setTaxNumberCountry',
        'trade_company_registration_location' => 'setTradeCompanyRegistrationLocation'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'address' => 'getAddress',
        'business_activity_code' => 'getBusinessActivityCode',
        'company_shareholders' => 'getCompanyShareholders',
        'identification_number' => 'getIdentificationNumber',
        'is_in_liquidation' => 'getIsInLiquidation',
        'legal_form' => 'getLegalForm',
        'local_tax_number' => 'getLocalTaxNumber',
        'local_tax_number_country' => 'getLocalTaxNumberCountry',
        'name' => 'getName',
        'organization_id' => 'getOrganizationId',
        'share_capital' => 'getShareCapital',
        'share_capital_currency' => 'getShareCapitalCurrency',
        'tax_identification_number' => 'getTaxIdentificationNumber',
        'tax_number_country' => 'getTaxNumberCountry',
        'trade_company_registration_location' => 'getTradeCompanyRegistrationLocation'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('business_activity_code', $data ?? [], null);
        $this->setIfExists('company_shareholders', $data ?? [], null);
        $this->setIfExists('identification_number', $data ?? [], null);
        $this->setIfExists('is_in_liquidation', $data ?? [], null);
        $this->setIfExists('legal_form', $data ?? [], null);
        $this->setIfExists('local_tax_number', $data ?? [], null);
        $this->setIfExists('local_tax_number_country', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('organization_id', $data ?? [], null);
        $this->setIfExists('share_capital', $data ?? [], null);
        $this->setIfExists('share_capital_currency', $data ?? [], null);
        $this->setIfExists('tax_identification_number', $data ?? [], null);
        $this->setIfExists('tax_number_country', $data ?? [], null);
        $this->setIfExists('trade_company_registration_location', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets address
     *
     * @return \cbdesk\Mirakl\Model\DR11Response200DataRecipientOrganizationAddress|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \cbdesk\Mirakl\Model\DR11Response200DataRecipientOrganizationAddress|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets business_activity_code
     *
     * @return string|null
     */
    public function getBusinessActivityCode()
    {
        return $this->container['business_activity_code'];
    }

    /**
     * Sets business_activity_code
     *
     * @param string|null $business_activity_code The business activity code of the organization.
     *
     * @return self
     */
    public function setBusinessActivityCode($business_activity_code)
    {
        if (is_null($business_activity_code)) {
            throw new \InvalidArgumentException('non-nullable business_activity_code cannot be null');
        }
        $this->container['business_activity_code'] = $business_activity_code;

        return $this;
    }

    /**
     * Gets company_shareholders
     *
     * @return string|null
     */
    public function getCompanyShareholders()
    {
        return $this->container['company_shareholders'];
    }

    /**
     * Sets company_shareholders
     *
     * @param string|null $company_shareholders Indicates if there is a single shareholder or several shareholders.
     *
     * @return self
     */
    public function setCompanyShareholders($company_shareholders)
    {
        if (is_null($company_shareholders)) {
            throw new \InvalidArgumentException('non-nullable company_shareholders cannot be null');
        }
        $this->container['company_shareholders'] = $company_shareholders;

        return $this;
    }

    /**
     * Gets identification_number
     *
     * @return string|null
     */
    public function getIdentificationNumber()
    {
        return $this->container['identification_number'];
    }

    /**
     * Sets identification_number
     *
     * @param string|null $identification_number The identification number of the organization.
     *
     * @return self
     */
    public function setIdentificationNumber($identification_number)
    {
        if (is_null($identification_number)) {
            throw new \InvalidArgumentException('non-nullable identification_number cannot be null');
        }
        $this->container['identification_number'] = $identification_number;

        return $this;
    }

    /**
     * Gets is_in_liquidation
     *
     * @return bool|null
     */
    public function getIsInLiquidation()
    {
        return $this->container['is_in_liquidation'];
    }

    /**
     * Sets is_in_liquidation
     *
     * @param bool|null $is_in_liquidation Indicates whether the company is in liquidation or not.
     *
     * @return self
     */
    public function setIsInLiquidation($is_in_liquidation)
    {
        if (is_null($is_in_liquidation)) {
            throw new \InvalidArgumentException('non-nullable is_in_liquidation cannot be null');
        }
        $this->container['is_in_liquidation'] = $is_in_liquidation;

        return $this;
    }

    /**
     * Gets legal_form
     *
     * @return string|null
     */
    public function getLegalForm()
    {
        return $this->container['legal_form'];
    }

    /**
     * Sets legal_form
     *
     * @param string|null $legal_form The legal form of the organization.
     *
     * @return self
     */
    public function setLegalForm($legal_form)
    {
        if (is_null($legal_form)) {
            throw new \InvalidArgumentException('non-nullable legal_form cannot be null');
        }
        $this->container['legal_form'] = $legal_form;

        return $this;
    }

    /**
     * Gets local_tax_number
     *
     * @return string|null
     */
    public function getLocalTaxNumber()
    {
        return $this->container['local_tax_number'];
    }

    /**
     * Sets local_tax_number
     *
     * @param string|null $local_tax_number The VAT/GST number.
     *
     * @return self
     */
    public function setLocalTaxNumber($local_tax_number)
    {
        if (is_null($local_tax_number)) {
            throw new \InvalidArgumentException('non-nullable local_tax_number cannot be null');
        }
        $this->container['local_tax_number'] = $local_tax_number;

        return $this;
    }

    /**
     * Gets local_tax_number_country
     *
     * @return string|null
     */
    public function getLocalTaxNumberCountry()
    {
        return $this->container['local_tax_number_country'];
    }

    /**
     * Sets local_tax_number_country
     *
     * @param string|null $local_tax_number_country The local tax number country of the organization.
     *
     * @return self
     */
    public function setLocalTaxNumberCountry($local_tax_number_country)
    {
        if (is_null($local_tax_number_country)) {
            throw new \InvalidArgumentException('non-nullable local_tax_number_country cannot be null');
        }
        $this->container['local_tax_number_country'] = $local_tax_number_country;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The organization name.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets organization_id
     *
     * @return string|null
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param string|null $organization_id Identifier of the customer organization
     *
     * @return self
     */
    public function setOrganizationId($organization_id)
    {
        if (is_null($organization_id)) {
            throw new \InvalidArgumentException('non-nullable organization_id cannot be null');
        }
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets share_capital
     *
     * @return float|null
     */
    public function getShareCapital()
    {
        return $this->container['share_capital'];
    }

    /**
     * Sets share_capital
     *
     * @param float|null $share_capital The share capital of the organization.
     *
     * @return self
     */
    public function setShareCapital($share_capital)
    {
        if (is_null($share_capital)) {
            throw new \InvalidArgumentException('non-nullable share_capital cannot be null');
        }
        $this->container['share_capital'] = $share_capital;

        return $this;
    }

    /**
     * Gets share_capital_currency
     *
     * @return string|null
     */
    public function getShareCapitalCurrency()
    {
        return $this->container['share_capital_currency'];
    }

    /**
     * Sets share_capital_currency
     *
     * @param string|null $share_capital_currency The share capital currency of the organization.
     *
     * @return self
     */
    public function setShareCapitalCurrency($share_capital_currency)
    {
        if (is_null($share_capital_currency)) {
            throw new \InvalidArgumentException('non-nullable share_capital_currency cannot be null');
        }
        $this->container['share_capital_currency'] = $share_capital_currency;

        return $this;
    }

    /**
     * Gets tax_identification_number
     *
     * @return string|null
     */
    public function getTaxIdentificationNumber()
    {
        return $this->container['tax_identification_number'];
    }

    /**
     * Sets tax_identification_number
     *
     * @param string|null $tax_identification_number The tax identification number of the organization.
     *
     * @return self
     */
    public function setTaxIdentificationNumber($tax_identification_number)
    {
        if (is_null($tax_identification_number)) {
            throw new \InvalidArgumentException('non-nullable tax_identification_number cannot be null');
        }
        $this->container['tax_identification_number'] = $tax_identification_number;

        return $this;
    }

    /**
     * Gets tax_number_country
     *
     * @return string|null
     */
    public function getTaxNumberCountry()
    {
        return $this->container['tax_number_country'];
    }

    /**
     * Sets tax_number_country
     *
     * @param string|null $tax_number_country The tax number country of the organization.
     *
     * @return self
     */
    public function setTaxNumberCountry($tax_number_country)
    {
        if (is_null($tax_number_country)) {
            throw new \InvalidArgumentException('non-nullable tax_number_country cannot be null');
        }
        $this->container['tax_number_country'] = $tax_number_country;

        return $this;
    }

    /**
     * Gets trade_company_registration_location
     *
     * @return string|null
     */
    public function getTradeCompanyRegistrationLocation()
    {
        return $this->container['trade_company_registration_location'];
    }

    /**
     * Sets trade_company_registration_location
     *
     * @param string|null $trade_company_registration_location The trade company registration location of the organization.
     *
     * @return self
     */
    public function setTradeCompanyRegistrationLocation($trade_company_registration_location)
    {
        if (is_null($trade_company_registration_location)) {
            throw new \InvalidArgumentException('non-nullable trade_company_registration_location cannot be null');
        }
        $this->container['trade_company_registration_location'] = $trade_company_registration_location;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


