<?php
/**
 * PC01Response200FeaturesPricing
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  cbdesk\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mirakl Marketplace APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest-release
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace cbdesk\Mirakl\Model;

use \ArrayAccess;
use \cbdesk\Mirakl\ObjectSerializer;

/**
 * PC01Response200FeaturesPricing Class Doc Comment
 *
 * @category Class
 * @package  cbdesk\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PC01Response200FeaturesPricing implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PC01_Response_200_Features_Pricing';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'channel_pricing' => 'string',
        'discount_period_required' => 'bool',
        'scheduled_pricing' => 'bool',
        'volume_discount' => 'bool',
        'volume_pricing' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'channel_pricing' => null,
        'discount_period_required' => null,
        'scheduled_pricing' => null,
        'volume_discount' => null,
        'volume_pricing' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'channel_pricing' => false,
        'discount_period_required' => false,
        'scheduled_pricing' => false,
        'volume_discount' => false,
        'volume_pricing' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'channel_pricing' => 'channel_pricing',
        'discount_period_required' => 'discount_period_required',
        'scheduled_pricing' => 'scheduled_pricing',
        'volume_discount' => 'volume_discount',
        'volume_pricing' => 'volume_pricing'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'channel_pricing' => 'setChannelPricing',
        'discount_period_required' => 'setDiscountPeriodRequired',
        'scheduled_pricing' => 'setScheduledPricing',
        'volume_discount' => 'setVolumeDiscount',
        'volume_pricing' => 'setVolumePricing'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'channel_pricing' => 'getChannelPricing',
        'discount_period_required' => 'getDiscountPeriodRequired',
        'scheduled_pricing' => 'getScheduledPricing',
        'volume_discount' => 'getVolumeDiscount',
        'volume_pricing' => 'getVolumePricing'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('channel_pricing', $data ?? [], null);
        $this->setIfExists('discount_period_required', $data ?? [], null);
        $this->setIfExists('scheduled_pricing', $data ?? [], null);
        $this->setIfExists('volume_discount', $data ?? [], null);
        $this->setIfExists('volume_pricing', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets channel_pricing
     *
     * @return string|null
     */
    public function getChannelPricing()
    {
        return $this->container['channel_pricing'];
    }

    /**
     * Sets channel_pricing
     *
     * @param string|null $channel_pricing Allows sellers to create prices applicable on the operator’s different storefronts materialized as sales channels in Mirakl. DISABLED: No channel pricing. SINGLE: Allows sellers to create one price per channel. MULTI: Allows sellers to create multiple prices per channel.
     *
     * @return self
     */
    public function setChannelPricing($channel_pricing)
    {
        if (is_null($channel_pricing)) {
            throw new \InvalidArgumentException('non-nullable channel_pricing cannot be null');
        }
        $this->container['channel_pricing'] = $channel_pricing;

        return $this;
    }

    /**
     * Gets discount_period_required
     *
     * @return bool|null
     */
    public function getDiscountPeriodRequired()
    {
        return $this->container['discount_period_required'];
    }

    /**
     * Sets discount_period_required
     *
     * @param bool|null $discount_period_required Requires sellers to set start and end dates when creating or updating discounts on default and specific prices.
     *
     * @return self
     */
    public function setDiscountPeriodRequired($discount_period_required)
    {
        if (is_null($discount_period_required)) {
            throw new \InvalidArgumentException('non-nullable discount_period_required cannot be null');
        }
        $this->container['discount_period_required'] = $discount_period_required;

        return $this;
    }

    /**
     * Gets scheduled_pricing
     *
     * @return bool|null
     */
    public function getScheduledPricing()
    {
        return $this->container['scheduled_pricing'];
    }

    /**
     * Sets scheduled_pricing
     *
     * @param bool|null $scheduled_pricing Allows sellers to set up multiple prices in advance
     *
     * @return self
     */
    public function setScheduledPricing($scheduled_pricing)
    {
        if (is_null($scheduled_pricing)) {
            throw new \InvalidArgumentException('non-nullable scheduled_pricing cannot be null');
        }
        $this->container['scheduled_pricing'] = $scheduled_pricing;

        return $this;
    }

    /**
     * Gets volume_discount
     *
     * @return bool|null
     */
    public function getVolumeDiscount()
    {
        return $this->container['volume_discount'];
    }

    /**
     * Sets volume_discount
     *
     * @param bool|null $volume_discount Allows discounts for bulk purchases
     *
     * @return self
     */
    public function setVolumeDiscount($volume_discount)
    {
        if (is_null($volume_discount)) {
            throw new \InvalidArgumentException('non-nullable volume_discount cannot be null');
        }
        $this->container['volume_discount'] = $volume_discount;

        return $this;
    }

    /**
     * Gets volume_pricing
     *
     * @return bool|null
     */
    public function getVolumePricing()
    {
        return $this->container['volume_pricing'];
    }

    /**
     * Sets volume_pricing
     *
     * @param bool|null $volume_pricing Allows pricing for bulk purchases
     *
     * @return self
     */
    public function setVolumePricing($volume_pricing)
    {
        if (is_null($volume_pricing)) {
            throw new \InvalidArgumentException('non-nullable volume_pricing cannot be null');
        }
        $this->container['volume_pricing'] = $volume_pricing;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


