<?php
/**
 * PC01Response200FeaturesOrderWorkflows
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  cbdesk\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mirakl Marketplace APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest-release
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace cbdesk\Mirakl\Model;

use \ArrayAccess;
use \cbdesk\Mirakl\ObjectSerializer;

/**
 * PC01Response200FeaturesOrderWorkflows Class Doc Comment
 *
 * @category Class
 * @package  cbdesk\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PC01Response200FeaturesOrderWorkflows implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PC01_Response_200_Features_OrderWorkflows';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'no_customer_payment_confirmation' => 'bool',
        'order_acceptance' => 'string',
        'pause_debit_workflow' => 'bool',
        'pay_on_due_date' => 'bool',
        'pay_on_shipment' => 'bool',
        'sellers_edit_shipping_origin' => 'bool',
        'shipping_and_billing_details_before_acceptance' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'no_customer_payment_confirmation' => null,
        'order_acceptance' => null,
        'pause_debit_workflow' => null,
        'pay_on_due_date' => null,
        'pay_on_shipment' => null,
        'sellers_edit_shipping_origin' => null,
        'shipping_and_billing_details_before_acceptance' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'no_customer_payment_confirmation' => false,
        'order_acceptance' => false,
        'pause_debit_workflow' => false,
        'pay_on_due_date' => false,
        'pay_on_shipment' => false,
        'sellers_edit_shipping_origin' => false,
        'shipping_and_billing_details_before_acceptance' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'no_customer_payment_confirmation' => 'no_customer_payment_confirmation',
        'order_acceptance' => 'order_acceptance',
        'pause_debit_workflow' => 'pause_debit_workflow',
        'pay_on_due_date' => 'pay_on_due_date',
        'pay_on_shipment' => 'pay_on_shipment',
        'sellers_edit_shipping_origin' => 'sellers_edit_shipping_origin',
        'shipping_and_billing_details_before_acceptance' => 'shipping_and_billing_details_before_acceptance'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'no_customer_payment_confirmation' => 'setNoCustomerPaymentConfirmation',
        'order_acceptance' => 'setOrderAcceptance',
        'pause_debit_workflow' => 'setPauseDebitWorkflow',
        'pay_on_due_date' => 'setPayOnDueDate',
        'pay_on_shipment' => 'setPayOnShipment',
        'sellers_edit_shipping_origin' => 'setSellersEditShippingOrigin',
        'shipping_and_billing_details_before_acceptance' => 'setShippingAndBillingDetailsBeforeAcceptance'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'no_customer_payment_confirmation' => 'getNoCustomerPaymentConfirmation',
        'order_acceptance' => 'getOrderAcceptance',
        'pause_debit_workflow' => 'getPauseDebitWorkflow',
        'pay_on_due_date' => 'getPayOnDueDate',
        'pay_on_shipment' => 'getPayOnShipment',
        'sellers_edit_shipping_origin' => 'getSellersEditShippingOrigin',
        'shipping_and_billing_details_before_acceptance' => 'getShippingAndBillingDetailsBeforeAcceptance'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('no_customer_payment_confirmation', $data ?? [], null);
        $this->setIfExists('order_acceptance', $data ?? [], null);
        $this->setIfExists('pause_debit_workflow', $data ?? [], null);
        $this->setIfExists('pay_on_due_date', $data ?? [], null);
        $this->setIfExists('pay_on_shipment', $data ?? [], null);
        $this->setIfExists('sellers_edit_shipping_origin', $data ?? [], null);
        $this->setIfExists('shipping_and_billing_details_before_acceptance', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets no_customer_payment_confirmation
     *
     * @return bool|null
     */
    public function getNoCustomerPaymentConfirmation()
    {
        return $this->container['no_customer_payment_confirmation'];
    }

    /**
     * Sets no_customer_payment_confirmation
     *
     * @param bool|null $no_customer_payment_confirmation Allows seller payments to be completely separated from customer debits
     *
     * @return self
     */
    public function setNoCustomerPaymentConfirmation($no_customer_payment_confirmation)
    {
        if (is_null($no_customer_payment_confirmation)) {
            throw new \InvalidArgumentException('non-nullable no_customer_payment_confirmation cannot be null');
        }
        $this->container['no_customer_payment_confirmation'] = $no_customer_payment_confirmation;

        return $this;
    }

    /**
     * Gets order_acceptance
     *
     * @return string|null
     */
    public function getOrderAcceptance()
    {
        return $this->container['order_acceptance'];
    }

    /**
     * Sets order_acceptance
     *
     * @param string|null $order_acceptance Indicate if shop accounts must accept new orders and take responsibility for the transaction. NOT_AUTOMATIC: All shop accounts must accept their orders manually. AUTOMATIC: Orders are automatically accepted. BOTH: AUTOMATIC or NOT_AUTOMATIC mode depending on the store account
     *
     * @return self
     */
    public function setOrderAcceptance($order_acceptance)
    {
        if (is_null($order_acceptance)) {
            throw new \InvalidArgumentException('non-nullable order_acceptance cannot be null');
        }
        $this->container['order_acceptance'] = $order_acceptance;

        return $this;
    }

    /**
     * Gets pause_debit_workflow
     *
     * @return bool|null
     */
    public function getPauseDebitWorkflow()
    {
        return $this->container['pause_debit_workflow'];
    }

    /**
     * Sets pause_debit_workflow
     *
     * @param bool|null $pause_debit_workflow Pause the order debit workflow when taxes must be recalculated
     *
     * @return self
     */
    public function setPauseDebitWorkflow($pause_debit_workflow)
    {
        if (is_null($pause_debit_workflow)) {
            throw new \InvalidArgumentException('non-nullable pause_debit_workflow cannot be null');
        }
        $this->container['pause_debit_workflow'] = $pause_debit_workflow;

        return $this;
    }

    /**
     * Gets pay_on_due_date
     *
     * @return bool|null
     */
    public function getPayOnDueDate()
    {
        return $this->container['pay_on_due_date'];
    }

    /**
     * Sets pay_on_due_date
     *
     * @param bool|null $pay_on_due_date Allows professionals to pay their orders after the receipt of the items or an explicit invoice
     *
     * @return self
     */
    public function setPayOnDueDate($pay_on_due_date)
    {
        if (is_null($pay_on_due_date)) {
            throw new \InvalidArgumentException('non-nullable pay_on_due_date cannot be null');
        }
        $this->container['pay_on_due_date'] = $pay_on_due_date;

        return $this;
    }

    /**
     * Gets pay_on_shipment
     *
     * @return bool|null
     */
    public function getPayOnShipment()
    {
        return $this->container['pay_on_shipment'];
    }

    /**
     * Sets pay_on_shipment
     *
     * @param bool|null $pay_on_shipment Allows operators to debit orders before they have been fully shipped
     *
     * @return self
     */
    public function setPayOnShipment($pay_on_shipment)
    {
        if (is_null($pay_on_shipment)) {
            throw new \InvalidArgumentException('non-nullable pay_on_shipment cannot be null');
        }
        $this->container['pay_on_shipment'] = $pay_on_shipment;

        return $this;
    }

    /**
     * Gets sellers_edit_shipping_origin
     *
     * @return bool|null
     */
    public function getSellersEditShippingOrigin()
    {
        return $this->container['sellers_edit_shipping_origin'];
    }

    /**
     * Sets sellers_edit_shipping_origin
     *
     * @param bool|null $sellers_edit_shipping_origin Allow shop accounts to edit shipping origin to ensures accurate tax calculations with shipping origin data
     *
     * @return self
     */
    public function setSellersEditShippingOrigin($sellers_edit_shipping_origin)
    {
        if (is_null($sellers_edit_shipping_origin)) {
            throw new \InvalidArgumentException('non-nullable sellers_edit_shipping_origin cannot be null');
        }
        $this->container['sellers_edit_shipping_origin'] = $sellers_edit_shipping_origin;

        return $this;
    }

    /**
     * Gets shipping_and_billing_details_before_acceptance
     *
     * @return bool|null
     */
    public function getShippingAndBillingDetailsBeforeAcceptance()
    {
        return $this->container['shipping_and_billing_details_before_acceptance'];
    }

    /**
     * Sets shipping_and_billing_details_before_acceptance
     *
     * @param bool|null $shipping_and_billing_details_before_acceptance Indicate if shipping and billing details are displayed before order acceptance
     *
     * @return self
     */
    public function setShippingAndBillingDetailsBeforeAcceptance($shipping_and_billing_details_before_acceptance)
    {
        if (is_null($shipping_and_billing_details_before_acceptance)) {
            throw new \InvalidArgumentException('non-nullable shipping_and_billing_details_before_acceptance cannot be null');
        }
        $this->container['shipping_and_billing_details_before_acceptance'] = $shipping_and_billing_details_before_acceptance;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


