<?php
/**
 * PC01Response200FeaturesOrderWorkflowsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  cbdesk\Mirakl
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mirakl Marketplace APIs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: latest-release
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace cbdesk\Mirakl\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PC01Response200FeaturesOrderWorkflowsTest Class Doc Comment
 *
 * @category    Class
 * @description PC01Response200FeaturesOrderWorkflows
 * @package     cbdesk\Mirakl
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PC01Response200FeaturesOrderWorkflowsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PC01Response200FeaturesOrderWorkflows"
     */
    public function testPC01Response200FeaturesOrderWorkflows()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "no_customer_payment_confirmation"
     */
    public function testPropertyNoCustomerPaymentConfirmation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "order_acceptance"
     */
    public function testPropertyOrderAcceptance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pause_debit_workflow"
     */
    public function testPropertyPauseDebitWorkflow()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pay_on_due_date"
     */
    public function testPropertyPayOnDueDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pay_on_shipment"
     */
    public function testPropertyPayOnShipment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sellers_edit_shipping_origin"
     */
    public function testPropertySellersEditShippingOrigin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shipping_and_billing_details_before_acceptance"
     */
    public function testPropertyShippingAndBillingDetailsBeforeAcceptance()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
